version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: go-chat-postgres
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

volumes:
  postgres_data:

networks:
  chat-network:
    driver: bridge